name: open_edisu
description: An open source app to book EDISU study rooms.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_secure_storage: ^5.0.2
  http: ^0.13.4
  intl: ^0.17.0
  qr_flutter: ^4.0.0
    # Temporaly fix if we would want to upgrade to the latest version.
    # See https://github.com/theyakka/qr.flutter/issues/174
    # git:
    #   url: https://github.com/theyakka/qr.flutter.git
  horizontal_data_table: ^3.6.1+1
  charts_flutter: ^0.12.0
  flutter_bloc: ^8.0.1
  freezed: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  build_runner: ^2.1.8
  window_manager: ^0.2.2
  flutter_launcher_icons: ^0.9.2

flutter:
  uses-material-design: true

flutter_icons:
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#06446C"
  adaptive_icon_foreground: "assets/icon/foreground.png"
  android: true
  ios: true