name: open_edisu
description: An open source app to book EDISU study rooms.
publish_to: 'none'
version: 0.1.15+16

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_secure_storage: ^9.0.0
  intl: ^0.18.0
  qr_flutter: ^4.0.0
  horizontal_data_table: ^4.0.0
  flutter_bloc: ^8.0.1
  collection: ^1.18.0
  freezed_annotation: ^2.0.3
  get_it: ^7.6.7
  retrofit: ^4.0.3
  dio: ^5.4.0
  json_annotation: ^4.8.1
  pin_code_fields: ^8.0.1
  shared_preferences: ^2.2.2
  package_info_plus: ^5.0.1
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_hive_store: ^3.2.2
  path_provider: ^2.1.2
  url_launcher: ^6.2.4
  logging: ^1.0.2
  sticky_headers: ^0.3.0+2
  maps_launcher: ^2.0.1
  syncfusion_flutter_charts: ^24.2.4+3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  flutter_launcher_icons: ^0.13.1
  bloc_test: ^9.1.5
  freezed: ^2.4.6
  mockito: ^5.4.3
  json_serializable: ^6.2.0
  retrofit_generator: ^8.0.6
  pretty_dio_logger: ^1.2.0-beta-1
  msix: ^3.16.7

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icon/icon.png

flutter_icons:
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#06446C"
  adaptive_icon_foreground: "assets/icon/foreground.png"
  android: true
  ios: true

msix_config:
  display_name: Open Edisu
  publisher_display_name: Antonio Spadaro
  identity_name: 56649AntonioSpadaro.OpenEdisu
  publisher: CN=15FA372E-AC50-4E12-AFBB-C963287752A5
  msix_version: 1.1.15.0
  logo_path: .\assets\icon\icon.png
  capabilities: internetClient
  languages: en, it
