name: open_edisu
description: An open source app to book EDISU study rooms.
publish_to: 'none'
version: 0.1.5+6

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_secure_storage: ^5.0.2
  intl: ^0.17.0
  qr_flutter: ^4.0.0
    # Temporaly fix if we would want to upgrade to the latest version.
    # See https://github.com/theyakka/qr.flutter/issues/174
    # git:
    #   url: https://github.com/theyakka/qr.flutter.git
  horizontal_data_table: ^4.0.0
  charts_flutter: ^0.12.0
  flutter_bloc: ^8.0.1
  collection: ^1.15.0
  freezed_annotation: ^2.0.3
  window_manager: ^0.2.2
  get_it: ^7.2.0
  retrofit: ^3.0.1+1
  dio: ^4.0.6
  json_annotation: ^4.5.0
  pin_code_fields: ^7.4.0
  shared_preferences: ^2.0.15

dependency_overrides:
  json_serializable:
    git:
      url: https://github.com/google/json_serializable.dart
      path: json_serializable
  json_annotation:
    git:
      url: https://github.com/google/json_serializable.dart
      path: json_annotation

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  build_runner: ^2.1.8
  flutter_launcher_icons: ^0.9.2
  bloc_test: ^9.0.3
  freezed: ^2.0.2
  mockito: ^5.2.0
  json_serializable: ^6.2.0
  retrofit_generator: ^4.0.1
  pretty_dio_logger: ^1.2.0-beta-1

flutter:
  uses-material-design: true
  generate: true

flutter_icons:
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#06446C"
  adaptive_icon_foreground: "assets/icon/foreground.png"
  android: true
  ios: true