runs:
  using: "composite"
  steps:
    - name: Flutter action
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        cache: true

    - name: Get packages dependencies
      uses: ilovelinux/flutter-cache-action/pub/get@v1
      id: pub-cache
      with:
        pub-flags: --suppress-analytics
        enableCrossOsArchive: true

    - name: Get code generation dependencies
      uses: ilovelinux/flutter-cache-action/build_runner/build@v1
      id: build-cache
      with:
        key: build-runner-${{ runner.os }}-${{ hashFiles('pubspec.lock', '**/*.dart') }}
