runs:
  using: "composite"
  steps:
    - name: Flutter action
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        cache: true

    - name: Get packages dependencies
      run: flutter pub get --suppress-analytics
      shell: bash

    - name: Get code generation dependencies
      run: flutter pub run build_runner build
      shell: bash
