name: Dev builder

on:
  push:
    branches-ignore:
      - workflow-**
  pull_request:
  workflow_dispatch:

jobs:
  android:
    uses: ./.github/workflows/dev_android.yml

  windows:
    uses: ./.github/workflows/dev_windows.yml

  output:
    name: Job Summary
    needs: [android, windows]

    runs-on: ubuntu-latest
    if: ${{ always() }}

    steps:
      - name: Add job summary
        run: |
          echo "# Development builds :rocket:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Platform | Status |" >> $GITHUB_STEP_SUMMARY
          echo "| -------- | ------ |" >> $GITHUB_STEP_SUMMARY
          echo "| Android | ${{ needs.android.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Windows | ${{ needs.windows.result }} |" >> $GITHUB_STEP_SUMMARY
