on:
  workflow_call:
    inputs:
      run-tests:
        required: false
        type: boolean
        default: true

jobs:
  tests:
    runs-on: windows-latest
    if: ${{ inputs.run-tests }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Flutter
        uses: ./.github/actions/setup-flutter

      - name: Run tests
        run: flutter test --reporter expanded

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  build:
    runs-on: windows-latest

    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - uses: actions/checkout@v3

      - name: Setup Flutter
        uses: ./.github/actions/setup-flutter

      - name: Flutter Doctor
        run: flutter doctor -v

      - name: Build Windows package
        run: flutter build windows

      - name: Upload Windows package
        uses: actions/upload-artifact@v3
        with:
          name: windows-build
          path: build\windows\runner\Release
          if-no-files-found: error
