on:
  workflow_call:
    inputs:
      run-tests:
        required: false
        type: boolean
        default: true

jobs:
  tests:
    runs-on: macos-latest
    if: ${{ inputs.run-tests }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Flutter
        uses: ./.github/actions/setup-flutter

      - name: Run tests
        run: flutter test --reporter expanded

  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Flutter
        uses: ./.github/actions/setup-flutter

      - name: Flutter Doctor
        run: flutter doctor -v

      - name: Build binary
        run: flutter build macos

      - name: Create the DMG file
        run: |
          hdiutil create -format UDZO -srcfolder \
            build/macos/Build/Products/Release/open_edisu.app \
            build/macos/Build/Products/Release/open_edisu.dmg

      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: macos-dev
          path: build/macos/Build/Products/Release/open_edisu.dmg
          if-no-files-found: error
