name: Flutter Builder for Android

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Flutter action
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - run: flutter pub get
      # - run: flutter test
      - run: flutter build apk

      - uses: actions/upload-artifact@v3
        with:
          name: release
          path: build/app/outputs/flutter-apk/app-release.apk
