name: Flutter Builder for Android

on:
  push:
    branches-ignore:
      - workflow-**
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Flutter action
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - run: flutter doctor -v
      - run: flutter pub get
      - run: flutter pub run build_runner build
      - run: flutter test --coverage --reporter expanded
      - run: flutter build apk --flavor githubDebug

      - uses: actions/upload-artifact@v3
        with:
          name: github-build
          path: build/app/outputs/flutter-apk/app-githubdebug-release.apk
          if-no-files-found: error

      - name: Upload coverage reports to Codecov
        run: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov -t ${CODECOV_TOKEN}
