name: Prod builder

on:
  workflow_dispatch:
    inputs:
      run-tests:
        description: 'Run tests'
        required: false
        default: true
        type: boolean

jobs:
  android:
    uses: ./.github/workflows/prod_android.yml
    secrets: inherit
    with:
      run-tests: ${{ inputs.run-tests }}

  windows:
    uses: ./.github/workflows/prod_windows.yml
    with:
      run-tests: ${{ inputs.run-tests }}

  output:
    name: Job Summary
    needs: [android, windows]

    runs-on: ubuntu-latest
    if: ${{ always() }}

    steps:
      - name: Add job summary
        run: |
          echo "# Production builds :rocket:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Platform | Status |" >> $GITHUB_STEP_SUMMARY
          echo "| -------- | ------ |" >> $GITHUB_STEP_SUMMARY
          echo "| Android | ${{ needs.android.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Windows | ${{ needs.windows.result }} |" >> $GITHUB_STEP_SUMMARY
