on:
  workflow_call:
    inputs:
      run-tests:
        required: false
        type: boolean
        default: true

jobs:
  tests:
    runs-on: windows-latest
    if: ${{ inputs.run-tests }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Flutter
        uses: ./.github/actions/setup-flutter

      - name: Run tests
        run: flutter test --reporter expanded

  build:
    runs-on: windows-latest

    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - uses: actions/checkout@v3

      - name: Setup Flutter
        uses: ./.github/actions/setup-flutter

      - name: Build EXE package
        run: flutter build windows

      - name: Upload EXE package
        uses: actions/upload-artifact@v3
        with:
          name: windows-exe-build
          path: build\windows\x64\runner\Release\
          if-no-files-found: error

      - name: Build MSIX installer
        run: dart run msix:create --store --release

      - name: Upload MSIX installer
        uses: actions/upload-artifact@v3
        with:
          name: windows-msix-build
          path: build\windows\x64\runner\Release\open_edisu.msix
          if-no-files-found: error
